apiVersion: v1
kind: Service
metadata:
  name: jasminegraph-ui-frontend-service
  labels:
    application: jasminegraph-ui
spec:
  ports:
    - port: 3000
      name: "http"
      nodePort: 30080
  selector:
    service: jasminegraph-ui
    type: frontend
  type: NodePort

