import { ISelectProp } from "@/types/user-types";
import { ISelectNumProp } from './../types/user-types';

export enum AnalyzeOptions {
  TRIANGLECOUNT = "trian",
  // Add more options as needed
}

export enum InputTypes {
  SELECT = "select",
  INPUT = "input",
  INPUTNUMBER = "input_number",
  SWITCH = "switch"
}

export interface InputParam {
  label?: string;
  type: InputTypes;
  options?: ISelectProp[] | ISelectNumProp[];
}

// Define an interface for the input parameters for each analyzer option
export interface AnalyzerInput {
  // Example fields; adjust based on your specific analyzers
  [key: string]: InputParam
}

// Define an interface for the response generated by each analyzer
export interface AnalyzerResponse {
  success: boolean;
  data?: any;
  error?: string; // Optional error message
}

// Define an interface for each graph analyzer option
export interface GraphAnalyzer {
  id: AnalyzeOptions;
  name: string;
  description?: string;
  inputParameters: AnalyzerInput;
}

// Example of defining a specific analyzer
// const exampleAnalyzer: GraphAnalyzer = {
//   id: AnalyzeOptions.EXAMPLE,
//   name: "Example Analyzer",
//   description: "This is an example analyzer.",
//   inputParameters: {
//     // input
//     input: {
//       type: InputTypes.INPUT,
//       label: "Input",
//     },
//     // input number
//     inputNumber: {
//       type: InputTypes.INPUTNUMBER,
//       label: "Input Number",
//     },
//     // switch
//     switch: {
//       type: InputTypes.SWITCH,
//       label: "Switch",
//     },
//     // select
//     select: {
//       type: InputTypes.SELECT,
//       label: "Select",
//       options: [
//         { value: "option1", label: "Option 1" },
//         { value: "option2", label: "Option 2" },
//       ],
//     },
//   },
// }

export const triangleCountAnalyzer: GraphAnalyzer = {
  id: AnalyzeOptions.TRIANGLECOUNT,
  name: "Triangle Count",
  description: "Calculates the number of triangles in the graph.",
  inputParameters: {
      priority: {
        type:  InputTypes.SELECT,
        label: "Priority",
        options: [
          {value: "", label: "default"},
          { value: "1", label: "1" },
          { value: "2", label: "2" },
          { value: "3", label: "3" },

        ],
      },
  }
};

export const Analyzers: GraphAnalyzer[] = [
  // exampleAnalyzer,
  triangleCountAnalyzer
  // Add more analyzers as needed
];
