/**
Copyright 2024 JasmineGraph Team
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 */

import { ISelectProp } from "@/types/user-types";
import { ISelectNumProp } from './../types/user-types';

export enum AnalyzeOptions {
  TRIANGLECOUNT = "trian",
  // Add more options as needed
}

export enum InputTypes {
  SELECT = "select",
  INPUT = "input",
  INPUTNUMBER = "input_number",
  SWITCH = "switch"
}

export interface InputParam {
  label?: string;
  type: InputTypes;
  options?: ISelectProp[] | ISelectNumProp[];
}

// Define an interface for the input parameters for each analyzer option
export interface AnalyzerInput {
  // Example fields; adjust based on your specific analyzers
  [key: string]: InputParam
}

// Define an interface for the response generated by each analyzer
export interface AnalyzerResponse {
  success: boolean;
  data?: any;
  error?: string; // Optional error message
}

// Define an interface for each graph analyzer option
export interface GraphAnalyzer {
  id: AnalyzeOptions;
  name: string;
  description?: string;
  inputParameters: AnalyzerInput;
}

export const triangleCountAnalyzer: GraphAnalyzer = {
  id: AnalyzeOptions.TRIANGLECOUNT,
  name: "Triangle Count",
  description: "Calculates the number of triangles in the graph.",
  inputParameters: {
      priority: {
        type:  InputTypes.SELECT,
        label: "Priority",
        options: [
          {value: "", label: "default"},
          { value: "1", label: "1" },
          { value: "2", label: "2" },
          { value: "3", label: "3" },

        ],
      },
  }
};

export const Analyzers: GraphAnalyzer[] = [
  triangleCountAnalyzer
  // Add more analyzers as needed
];
